version: '2'
services:
  web:
    build: ./nodejs
    volumes:
      - ./nodejs:/app
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    build: ./mongo
    ports:
      - 27017:27017
    volumes:  
      - mongodbdata:/containerdb
volumes:
  mongodbdata:
