db:
   image: postgres:9.4
   environment:
      - POSTGRES_USER=postgres
      - PGPASSWORD=postgres 
      - POSTGRES_PASSWORD=postgres
   ports:
      - "15432:5432"  
   volumes:
      - ./postgresql/data:/var/lib/postgresql/data